#!/usr/bin/expect
# echo "123456" | passwd --stdin admin
# Script function : One click to make ssh safly.
# Script version : 1.0
# Author : yoo@yoo.hk
# Made : 2013.09.01
# Support : Only CentOS 6.0+

spawn ssh-keygen -t rsa
expect "save the key"
send "\r"
expect "passphrase"
send "\r"
expect "same passphrase"
send "\r"
expect eof

spawn ssh-keygen -t rsa -f /root/.ssh/id_rsa_github
expect "passphrase"
send "\r"
expect "same passphrase"
send "\r"
expect eof

spawn ssh-keygen -t rsa -f /root/.ssh/id_rsa_oschina
expect "passphrase"
send "\r"
expect "same passphrase"
send "\r"
expect eof

exec sh sshchport.sh
